defaults:
  - model: mae
  - writer: cometml
  - metrics: example
  - datasets: stl10
  - dataloader: example
  - transforms: stl10_no_augs
  - _self_

optimizer:
  _target_: torch.optim.AdamW
  lr:  1.5e-4
  weight_decay: 0.05

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${trainer.n_epochs}

loss_function:
  _target_: src.loss.pixel_reconstruction_loss.PixelReconstructionLoss
  criterion: L2

metrics:
  train: []
  inference: []

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: null  # null means epoch-based training (use full dataset)
  device_tensors: ["images", "raw_images"]  # which tensors should be on device
  resume_from: null  # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto  # device name or "auto"
  override: True  # if True, will override the previous run with the same name
  monitor: "min loss"  # "off" or "max/min metric_name", for MAE we minimize loss
  save_period: 10  # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs}  # epochs for early stopping
  save_dir: "saved"
  seed: 42

