defaults:
  - model: vit_sup
  - writer: cometml
  - metrics: example
  - datasets: stl10_onebatch
  - dataloader: example
  - transforms: stl10
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 0.01
lr_scheduler: 
  _target_: torch.optim.lr_scheduler.OneCycleLR 
  max_lr: ${optimizer.lr} 
  epochs: ${trainer.n_epochs} 
  steps_per_epoch: ${trainer.epoch_len} 
  pct_start: 0.05
loss_function:
  _target_: src.loss.ClassificationLoss
  type: "CrossEntropyLoss"
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["images", "labels"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max test_MulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
