train:
  image: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.RandomResizedCrop
        size: [96, 96]
        scale: [0.75, 1.0]
        ratio: [0.75, 1.33333333333333]
        antialias: True
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.v2.RandomApply
        p: 0.8
        transforms:
          - _target_: torchvision.transforms.v2.ColorJitter
            brightness: [0.6, 1.7]
            contrast: [0.6, 1.4]
            saturation: [0.8, 1.2]
            hue: [-0.1, 0.1]
      - _target_: torchvision.transforms.v2.RandomApply
        p: 0.1
        transforms:
          - _target_: torchvision.transforms.v2.GaussianBlur
            kernel_size: 5
      - _target_: torchvision.transforms.v2.RandomRotation
        degrees: 7
      - _target_: torchvision.transforms.v2.RandomInvert
        p: 0.1
  image2: ${transforms.instance_transforms.train.image}
  raw_image: ${transforms.instance_transforms.inference.raw_image}

inference:
  image: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToTensor
  image2: ${transforms.instance_transforms.inference.image}
  raw_image: ${transforms.instance_transforms.inference.image}
