train:
  image: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToTensor
  image2: ${transforms.instance_transforms.train.image}
  raw_image: ${transforms.instance_transforms.inference.raw_image}

inference:
  image: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToTensor
      # - _target_: torchvision.transforms.v2.Normalize
      #   mean: [0.4467, 0.4398, 0.4066]
      #   std: [0.2242, 0.2215, 0.2239]
  image2: ${transforms.instance_transforms.inference.image}
  raw_image: ${transforms.instance_transforms.inference.image}
