train:
  image: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.Resize
        size: 64
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
  image2:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.Resize
        size: 64
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
  raw_image:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.Resize
        size: 64
